# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
